### ISSUE TITLE
Please Collaborate With Zerobase!

### ISSUE THREAD

**Issue by aronszanto** [ehidra/contact-tracer#10]
Hello contact-tracer friends. I'm Aron Szanto. I'm leading a team of 120 volunteers to build an anonymous, virtual contact tracing application called Zerobase. We'd love to connect with you.

Zerobase is a different kind of contact tracing. We don't use GPS, proximity sensing, peer to peer systems, or app installs. Instead, our novel QR mesh network can be deployed into any community with access to a printer. We're on the ground in Germany already around Köln and are moving quickly towards a scaled deployment in the USA: New Jersey, New York, California, Texas, Colorado, and New Hampshire. 

I love the work you're doing here. Please consider getting in touch with us- we know that the eventual technical system that will be most effective against the coronavirus is a consortium solution, combining proximity, GPS, touchpoint-based mechanisms (like ours), and many other ingenious mechanisms developed under the auspices of the worldwide effort to end COVID-19. We have designed our system and models from the ground up to be able to quickly integrate with any other application that may provide helpful information, and we will prioritize sharing any information, data, or analysis that arises out of the use of our system.

In the meantime, if you're interested in working with us, please read about us at https://github.com/zerobase-io/About-Us-Onboarding. And for those who will see contact-tracer through, please keep in touch! We'd love to share data with you- our orthogonal modalities of tracing will bring synergy when analyzing the spread of the virus.

Love from the front,

Aron Szanto
Founder and CEO,
Zerobase Foundation

**Comment by baradhili** [comment]
Thanks Aron... does your system provide identifiable information on a trace, or is it primarily concerned about tracing spread of covid anonymously?

**Comment by aronszanto** [comment]
Very cool, thanks for the tip. We are building tracing networks out of real human checkins that are anonymous. Crucially, we're not asking people to download an application, which solves the single greatest hurdle in technological contact tracing systems in liberal societies- the network effect of application adoption. Because we're install-free, we can onboard the billions of people in the world who have a smartphone in 2 seconds just by asking them to open their camera app. 

Check out our onboarding repo or https://zerobase.io for more!

**Comment by baradhili** [comment]
yup - you don't need to sell to us.. please :)

**Comment by aronszanto** [comment]
Just making some good friends and preaching to the choir :) Let's keep in touch.

**Comment by cmorillo** [comment]
Thanks, we are going and focus on release and then we can see what we do from there :)

**Comment by aronszanto** [comment]
@cmorillo could I ask that you please consider reopening this for visibility? I find that people who read about these opportunities for collaboration are able to design even better technology when they think about how we may want to share data across several platforms in the long run. 

Of course you and the team are currently focused on releasing your awesome app- just hoping that people see this, read about what we're doing, and are able to think ahead about how to use us as a force multiplier to make your tech even more awesome. Thank you!!

**Comment by baradhili** [comment]
@aronszanto The trouble is.. we are getting lots of people asking, but very few actually willing to contribute.. so we end up spending cycles in discussion where nothing occurs.. 

Normally, if people want to help on Github etc.. they fork the repo, do development and create a pull request..

Right now we are in a bit of a holding pattern.. seeing what is going to happen from Singapore's sharing of their code with governments...
