### ISSUE TITLE
Credential 

### ISSUE THREAD

**Issue by sagaraher** [ehidra/contact-tracer#13]
Hello Team ,

I am trying to run this ionic project in local .
I need some credential details , you have this ?
firebase: {
        apiKey: '',
        authDomain: '',
        databaseURL: '',
        projectId: '',
        storageBucket: '',
        messagingSenderId: '',
        appId: '',
        measurementId: ''
    }

**Comment by baradhili** [comment]
you need to setup your own firebase...
