### ISSUE TITLE
How you are advertising a unique id?

### ISSUE THREAD

**Issue by symun92** [ehidra/contact-tracer#20]
Can you inform me how you are advertising a unique id? And how can device detect that unique id during scan?
I am using same plugin https://github.com/randdusing/cordova-plugin-bluetoothle
I am adverting like this
bluetoothle.startAdvertising(sucess, error, {
          "services":["xxx"], //iOS
          "service":"xxx", //Android
          "name":"xxxxx",
        });
But problem is that during scan I am getting a string. But how can I advertise a unique id?
advertisement:"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx" //This is for example

**Comment by baradhili** [comment]
this project halted back in April once Singapore open sourced their code.. best to go to https://github.com/opentrace-community and ask there..
