### ISSUE TITLE
stick to BLE, avoid GPS

### ISSUE THREAD

**Issue by baradhili** [ehidra/contact-tracer#3]
in open-air Bluetooth and wifi have really long ranges... BLE is pretty much designed for short-range (yeah it can still see far, but less likely)

Not sure if you are looking at GPS tracking, but remember the GPS receiver really sucks down on the battery - I did have a thought that the protocol get extended so the user can be advised if they've been close to a confirmed case within the last 14/21 days.. and if they are, they can pass their current location back to authorities..

**Comment by waqarrashid33** [comment]
Do you know if we can add the user ID in advertisement packets?

**Comment by baradhili** [comment]
it looks like we need to use a couple of profiles..
1. the PXP profile detects devices based on signal strength.. this will give us the "within 2m" indicator.. we might be able to link device MAC/ID to the user ID and stop there.. or we might need to use 
2. the UDS - which is a generic user data profile

**Comment by waqarrashid33** [comment]
You should ask them to add you to their slack group. I am not an Android developer so Android side of BLE is a bit unclear to me. I am embedded developer and still learning BLE.

**Comment by baradhili** [comment]
I have, but they are UK based so won't be online yet... though you are in Germany?

**Comment by baradhili** [comment]
here is a good run down of the scan protocol and what can be returned in the advertisement messages.. https://devzone.nordicsemi.com/nordic/short-range-guides/b/bluetooth-low-energy/posts/ble-central-tutorial - about half way down the page

**Comment by baradhili** [comment]
so you could build a db on the device of device UUIDs and the time you saw them and the time you stop seeing them... technically you should be able to keep this on the device without issue since the number _should_ be low!.. 
but maybe just in case, any time we see an internet connection we sync this back to the central server with out device UUID tagged against it.. with the server, maybe if we used a couch/mongo type db it might be more resilient..

**Comment by baradhili** [comment]
iOS scanning example https://stackoverflow.com/questions/10178293/how-to-get-list-of-available-bluetooth-devices

**Comment by cmorillo** [comment]
Thanks, first version to be just BLE
