### ISSUE TITLE
Feature request: QR code base contact

### ISSUE THREAD

**Issue by waqarrashid33** [ehidra/contact-tracer#4]
User scans the QR code of other user or place and that makes an entry in the database about that contact. Just a rough idea

**Comment by 8lenka8** [comment]
QR codes are great at preserving anonymity but if we could make it more friction-less so users don't need to do anything... Maybe qr codes can be used by nhs, to get confirmed cases to scan them to let the app know this case is real and not prank?

**Comment by waqarrashid33** [comment]
Another benefit of QR code is that both parties won't need a smart phone to
register a contact. One can simply scan anothers qr code and it will be
taken as a contact between the two users at that location and time.

**Comment by aronszanto** [comment]
Hi folks, please see #10, we're doing exactly this.

**Comment by cmorillo** [comment]
We are focused on BLE by now, same thing but no need from interaction, we get time , rssi (signal streght) and UUID from the other app

**Comment by aronszanto** [comment]
Cool, @cmorillo! Consider us friends- you get interaction-free traffic, but we get download-free traffic. Hopefully we can combine data + forces one day. Keep us in mind :)
