### ISSUE TITLE
From Tracing to Preemption

### ISSUE THREAD

**Issue by DavidStodolsky** [ehidra/contact-tracer#8]
http://cosmism.blogspot.com/2020/03/from-tracing-to-preemption.html

https://github.com/BDI-pathogens/covid-19_instant_tracing/blob/master/Policy%20forum%20-%20COVID-19%20containment%20by%20herd%20protection.pdf

**Comment by DavidStodolsky** [comment]
https://045.medsci.ox.ac.uk/mobile-app

**Comment by cmorillo** [comment]
Hi @DavidStodolsky that is actually the document we started this app for:
https://045.medsci.ox.ac.uk/mobile-app

Is our intention :)
