### ISSUE TITLE
how can I run this in Android Studio in Windows

### ISSUE THREAD

**Issue by kirtish10** [ehidra/contact-tracer#9]
please list the steps

**Comment by harshitsilly** [comment]
@kirtish10 man. this is a javascript project.. built on ionic framework..  just install vs code on your windows. I f you have node installed.. then proceed with the ionic installation.  After that, you can build your android/ios application. If u are a web developer than u should be knowing these steps. For more details visit ionic website.

**Comment by cmorillo** [comment]
Also at some point we will release documentation, is all in progress as we are adding backend with Firebase so we have full example, give us a week please :)

**Comment by kirtish10** [comment]
> @kirtish10 man. this is a javascript project.. built on ionic framework.. just install vs code on your windows. I f you have node installed.. then proceed with the ionic installation. After that, you can build your android/ios application. If u are a web developer than u should be knowing these steps. For more details visit ionic website.

thanks man...it worked

**Comment by kirtish10** [comment]
> Also at some point we will release documentation, is all in progress as we are adding backend with Firebase so we have full example, give us a week please :)

you all are doing great
